# k8s/backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-exp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-exp-backend
  template:
    metadata:
      labels:
        app: travel-exp-backend
    spec:
      containers:
      - name: backend
        image: aeroserg/travel-exp-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URI
          value: mongodb://root:adjalbv&bskdf2Bk1BC3keJ!Jk13@mongo-svc:27017/travel-exp?authSource=admin
        - name: PORT
          value: "4000"
        - name: NODE_OPTIONS
          value: "--max-old-space-size=1536"
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 1000m
            memory: 2048Mi

---

apiVersion: v1
kind: Service
metadata:
  name: travel-exp-backend-svc
  labels:
    app: travel-exp-backend
    release: prometheus
spec:
  type: ClusterIP
  selector:
    app: travel-exp-backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
